### ISSUE TITLE
"g commit --amend" issues

### ISSUE THREAD

**Issue by ozcanovunc** [evansendra/mingit#12]
I wanted to change my commit message by running
- g commit --amend -m "Save theme related configuration under state.theme"

But it gave me errors like
- error: pathspec 'theme' did not match any file(s) known to git.
- error: pathspec 'related' did not match any file(s) known to git.
- error: pathspec 'configuration' did not match any file(s) known to git.
- error: pathspec 'under' did not match any file(s) known to git.
- error: pathspec 'state.theme' did not match any file(s) known to git.

In the same way, when I run 
- g commit --amend -m "Save theme"

I end up with following error as well
- error: pathspec 'theme' did not match any file(s) known to git.

However **g commit --amend -m "Save theme"** works fine
**git commit --amend -m "Save theme"** works also fine

**Comment by evansendra** [comment]
Hi @ozcanovunc I'm not sure if you're still using this alias, but I was able to make the issue go away by running 

    git commit --amend -m "Save theme"

after which 

    g commit --amend -m "Save theme"

worked

Does it fix the issue for you as well?

**Comment by evansendra** [comment]
closing for now please re-open if you need help
