### ISSUE TITLE
Feature Request: support for git commit

### ISSUE THREAD

**Issue by ghost** [evansendra/mingit#13]
It would be nice if `g c` was the equivalent of writing `git commit`. Current `g c` defaults to `git commit -m`. The `-m` argument requiring a text message. This is particularly useful when using `.gitmessage` files such as this one:

https://gist.github.com/josephmcasey/1901f0e12065b4e36cde287b2118eb43

**Comment by favna** [comment]
Seconding this as it would be nice to do `g c --amend` etc or heck even a specific shortcut for amending in `g c a` or `g ca`

**Comment by evansendra** [comment]
Implemented in 9ea4036be5e50ac4c41ea766485855cbd6f5571c
